export { default as myProfile } from "./My.png";
export { default as myHeart } from "./Heart.png";
export { default as myUnion } from "./Union.png";
export { default as searchOnNavbar } from "./Search.png";
export { default as call } from "./Call.png";
export { default as face } from "./Facebook.png";
export { default as insta } from "./Insta.png";
export { default as twitter } from "./Twitter.png";
export { default as youtube } from "./Youtube.png";
